### ISSUE TITLE
开启隐藏底部按钮后无法进入设置

### ISSUE THREAD

**Issue by github-h** [ejiaogl/FuckCoolapk#11]
小米11 magisk v22➕lsp1.1.0(5368)
![Screenshot_2021-03-05-01-57-14-139_com coolapk market](https://user-images.githubusercontent.com/49114731/110008721-0128a600-7d57-11eb-91bf-4c72279ead8e.jpg)
![Screenshot_2021-03-05-01-58-33-361_com coolapk market](https://user-images.githubusercontent.com/49114731/110008892-392fe900-7d57-11eb-83e0-f8fd937c746e.jpg)
都是最新的版本
只要开了隐藏低栏就啥都没有了 不是应该保留我的么？
只能清楚应用数据才行
希望修复一下这个功能
需要我提供什么log可以说

**Comment by ejiaogl** [comment]
经过多次反复测试都无法重现该问题,请尝试更新酷安到最新版本

**Comment by github-h** [comment]
11.0.2难道不是最新版本嘛？第二张图不是有target version而且不止我一个人有这个问题 我也遇到其他人有说过  怎么抓log可能会有帮助呢？

**Comment by github-h** [comment]
![Screenshot_2021-03-05-02-55-44-346_org telegram messenger](https://user-images.githubusercontent.com/49114731/110015022-67fd8d80-7d5e-11eb-8b6e-809c7966ac03.jpg)
这其他人也遇到了和我一样的问题

**Comment by ejiaogl** [comment]
> ![Screenshot_2021-03-05-02-55-44-346_org telegram messenger](https://user-images.githubusercontent.com/49114731/110015022-67fd8d80-7d5e-11eb-8b6e-809c7966ac03.jpg)
> 这其他人也遇到了和我一样的问题

1. 卸载模块
2. 进入酷安截图主界面上传到这里
3. 打开隐藏底部按钮开关
4. 清理LSP日志
5. 打开酷安
6. 上传LSP日志到这里

**Comment by ejiaogl** [comment]
> > ![Screenshot_2021-03-05-02-55-44-346_org telegram messenger](https://user-images.githubusercontent.com/49114731/110015022-67fd8d80-7d5e-11eb-8b6e-809c7966ac03.jpg)
> > 这其他人也遇到了和我一样的问题
> 
> 1. 卸载模块
> 2. 进入酷安截图主界面上传到这里
> 3. 打开隐藏底部按钮开关
> 4. 清理LSP日志
> 5. 打开酷安
> 6. 上传LSP日志到这里

麻烦按照以上顺序操作一遍，并把日志上传我好分析原因，我先睡了明天还有事

**Comment by github-h** [comment]
感觉没抓到啥有用的日志 首先modules log为空 verbose抓到了一些
```
03-05 09:37:14.553  1484  3068 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10274, callingPid=2760
03-05 09:37:14.554   850  1049 D LSPosedService: returned service
03-05 09:37:14.555  1484  3068 D LSPosedService: got binder is android.os.BinderProxy@cde45d2
03-05 09:37:14.557  2760  2760 I LSPosed : Start to install inline hooks
03-05 09:37:14.557  2760  2760 I LSPosed : Using api level 30
03-05 09:37:14.557  2760  2760 I LSPosed : Start to install Riru hook
03-05 09:37:14.557  2760  2760 I LSPosed : Riru hooks installed
03-05 09:37:14.565  2760  2760 I LSPosed : ART hooks installed
03-05 09:37:14.583  2760  2760 I LSPosed : Loading modules for com.coolapk.market
03-05 09:37:14.584  2760  2760 I LSPosed-Bridge: Loading modules from /data/app/~~6vscI0XmPi139WewXFyrfA==/com.fuckcoolapk-vF0nnThFTq-G3sixvA8sDQ==/base.apk
03-05 09:37:14.590  2760  2760 I LSPosed-Bridge:   Loading class com.fuckcoolapk.InitHook
03-05 09:37:16.156   850  1049 D LSPosedService: New installed: com.coolapk.market
03-05 09:37:42.467  1484  6055 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10083, callingPid=2761
03-05 09:37:42.468   850  1049 D LSPosedService: Skipped com.mobiletools.systemhelper:register/10083
03-05 09:37:43.626  1484  3040 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10120, callingPid=14475
03-05 09:37:43.627   850  1049 D LSPosedService: Skipped com.miui.systemAdSolution/10120
03-05 09:37:43.854  1484  6060 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10120, callingPid=14560
03-05 09:37:43.855   850  1049 D LSPosedService: Skipped com.miui.systemAdSolution:ui/10120
03-05 09:37:49.410  1484  4781 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=2767
03-05 09:37:49.410   850  1049 D LSPosedService: Skipped com.miui.securitycenter/1000
03-05 09:37:50.967   850  1049 D LSPosedService: pid=2760 uid=10274 is dead.
03-05 09:37:53.147  1484  3068 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10274, callingPid=2762
03-05 09:37:53.147   850  1049 D LSPosedService: returned service
03-05 09:37:53.148  1484  3068 D LSPosedService: got binder is android.os.BinderProxy@3a6d76d
03-05 09:37:53.151  2762  2762 I LSPosed : Start to install inline hooks
03-05 09:37:53.151  2762  2762 I LSPosed : Using api level 30
03-05 09:37:53.151  2762  2762 I LSPosed : Start to install Riru hook
03-05 09:37:53.151  2762  2762 I LSPosed : Riru hooks installed
03-05 09:37:53.161  2762  2762 I LSPosed : ART hooks installed
03-05 09:37:53.180  2762  2762 I LSPosed : Loading modules for com.coolapk.market
03-05 09:37:53.180  2762  2762 I LSPosed-Bridge: Loading modules from /data/app/~~6vscI0XmPi139WewXFyrfA==/com.fuckcoolapk-vF0nnThFTq-G3sixvA8sDQ==/base.apk
03-05 09:37:53.185  2762  2762 I LSPosed-Bridge:   Loading class com.fuckcoolapk.InitHook
03-05 09:37:54.742   850  1049 D LSPosedService: New installed: com.coolapk.market
03-05 09:37:57.521   850  1049 D LSPosedService: pid=2762 uid=10274 is dead.
03-05 09:38:20.843  1484  3042 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=15060
03-05 09:38:20.843   850  1049 D LSPosedService: Skipped com.miui.screenshot/1000
03-05 09:38:25.403  1484  4758 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=12899
03-05 09:38:25.404   850  1049 D LSPosedService: Skipped android:ui/1000
03-05 09:38:30.980  1484  6060 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10103, callingPid=12901
03-05 09:38:30.980   850  1049 D LSPosedService: Skipped com.google.android.documentsui/10103
```
卸载完模块的图在这里
![Screenshot_2021-03-05-09-28-43-949_com coolapk market](https://user-images.githubusercontent.com/49114731/110055031-2b9a5380-7d97-11eb-846a-86c257547bbe.jpg)


我不是很懂你这顺序是啥 只有卸载没有启用模块嘛？
我就按照以下顺序来的
1.正常开启模块打开酷安同意用户协议
2.此时没有启用任何选项，然后勾选隐藏低栏
3.杀掉酷安
4.进入lsp清理日志
5.打开酷安
6.进入lsp保存日志

不知道这样对不对(虽然感觉没抓到啥log) 麻烦你了

**Comment by ejiaogl** [comment]
> 感觉没抓到啥有用的日志 首先modules log为空 verbose抓到了一些
> 
> ```
> 03-05 09:37:14.553  1484  3068 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10274, callingPid=2760
> 03-05 09:37:14.554   850  1049 D LSPosedService: returned service
> 03-05 09:37:14.555  1484  3068 D LSPosedService: got binder is android.os.BinderProxy@cde45d2
> 03-05 09:37:14.557  2760  2760 I LSPosed : Start to install inline hooks
> 03-05 09:37:14.557  2760  2760 I LSPosed : Using api level 30
> 03-05 09:37:14.557  2760  2760 I LSPosed : Start to install Riru hook
> 03-05 09:37:14.557  2760  2760 I LSPosed : Riru hooks installed
> 03-05 09:37:14.565  2760  2760 I LSPosed : ART hooks installed
> 03-05 09:37:14.583  2760  2760 I LSPosed : Loading modules for com.coolapk.market
> 03-05 09:37:14.584  2760  2760 I LSPosed-Bridge: Loading modules from /data/app/~~6vscI0XmPi139WewXFyrfA==/com.fuckcoolapk-vF0nnThFTq-G3sixvA8sDQ==/base.apk
> 03-05 09:37:14.590  2760  2760 I LSPosed-Bridge:   Loading class com.fuckcoolapk.InitHook
> 03-05 09:37:16.156   850  1049 D LSPosedService: New installed: com.coolapk.market
> 03-05 09:37:42.467  1484  6055 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10083, callingPid=2761
> 03-05 09:37:42.468   850  1049 D LSPosedService: Skipped com.mobiletools.systemhelper:register/10083
> 03-05 09:37:43.626  1484  3040 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10120, callingPid=14475
> 03-05 09:37:43.627   850  1049 D LSPosedService: Skipped com.miui.systemAdSolution/10120
> 03-05 09:37:43.854  1484  6060 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10120, callingPid=14560
> 03-05 09:37:43.855   850  1049 D LSPosedService: Skipped com.miui.systemAdSolution:ui/10120
> 03-05 09:37:49.410  1484  4781 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=2767
> 03-05 09:37:49.410   850  1049 D LSPosedService: Skipped com.miui.securitycenter/1000
> 03-05 09:37:50.967   850  1049 D LSPosedService: pid=2760 uid=10274 is dead.
> 03-05 09:37:53.147  1484  3068 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10274, callingPid=2762
> 03-05 09:37:53.147   850  1049 D LSPosedService: returned service
> 03-05 09:37:53.148  1484  3068 D LSPosedService: got binder is android.os.BinderProxy@3a6d76d
> 03-05 09:37:53.151  2762  2762 I LSPosed : Start to install inline hooks
> 03-05 09:37:53.151  2762  2762 I LSPosed : Using api level 30
> 03-05 09:37:53.151  2762  2762 I LSPosed : Start to install Riru hook
> 03-05 09:37:53.151  2762  2762 I LSPosed : Riru hooks installed
> 03-05 09:37:53.161  2762  2762 I LSPosed : ART hooks installed
> 03-05 09:37:53.180  2762  2762 I LSPosed : Loading modules for com.coolapk.market
> 03-05 09:37:53.180  2762  2762 I LSPosed-Bridge: Loading modules from /data/app/~~6vscI0XmPi139WewXFyrfA==/com.fuckcoolapk-vF0nnThFTq-G3sixvA8sDQ==/base.apk
> 03-05 09:37:53.185  2762  2762 I LSPosed-Bridge:   Loading class com.fuckcoolapk.InitHook
> 03-05 09:37:54.742   850  1049 D LSPosedService: New installed: com.coolapk.market
> 03-05 09:37:57.521   850  1049 D LSPosedService: pid=2762 uid=10274 is dead.
> 03-05 09:38:20.843  1484  3042 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=15060
> 03-05 09:38:20.843   850  1049 D LSPosedService: Skipped com.miui.screenshot/1000
> 03-05 09:38:25.403  1484  4758 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=1000, callingPid=12899
> 03-05 09:38:25.404   850  1049 D LSPosedService: Skipped android:ui/1000
> 03-05 09:38:30.980  1484  6060 D LSPosedService: onTransact: action=ACTION_GET_BINDER, callingUid=10103, callingPid=12901
> 03-05 09:38:30.980   850  1049 D LSPosedService: Skipped com.google.android.documentsui/10103
> ```
> 
> 卸载完模块的图在这里
> ![Screenshot_2021-03-05-09-28-43-949_com coolapk market](https://user-images.githubusercontent.com/49114731/110055031-2b9a5380-7d97-11eb-846a-86c257547bbe.jpg)
> 
> 我不是很懂你这顺序是啥 只有卸载没有启用模块嘛？
> 我就按照以下顺序来的
> 1.正常开启模块打开酷安同意用户协议
> 2.此时没有启用任何选项，然后勾选隐藏低栏
> 3.杀掉酷安
> 4.进入lsp清理日志
> 5.打开酷安
> 6.进入lsp保存日志
> 
> 不知道这样对不对(虽然感觉没抓到啥log) 麻烦你了

我知道啥原因了，你试试把你的机器语言设置会中文应该就好了，这个我晚上修复

**Comment by github-h** [comment]
哈哈哈哈哈哈原来是这个原因！感谢！

**Comment by ejiaogl** [comment]
晚上修吧，这个是我没想到的
