### ISSUE TITLE
coolapk_with_fuckcoolapk.apk 不能与 XPrivacyLua 一起使用

### ISSUE THREAD

**Issue by mclovin-2k** [ejiaogl/FuckCoolapk#17]
如果在 LSP Manager 里，打开 XPrivacyLua 的 Scope 里的 coolapk。
coolapk 运行时就会 FC。
异常日志：
[logcat.txt](https://github.com/ejiaogl/FuckCoolapk/files/6112865/logcat.txt)

**Comment by t0HiiBwn** [comment]
已经安装 lsposed 无需使用这个版本，直接下载模块即可。
