### ISSUE TITLE
希望添加新功能：长按“发现”打开消息中心

### ISSUE THREAD

**Issue by Thiasap** [ejiaogl/FuckCoolapk#19]
新版本把+号去掉了，消息中心太远单手有点累，想替换成长按进入消息中心。
没做过比较复杂的app，所以不会提pr，只能贴代码了
```Java
public void hookLoader(ClassLoader classLoader, Context ctx) throws Throwable {
        String HookActivity = "com.coolapk.market.view.main.MainFragment$setDiscoveryLongClick$1";
        String HookMethod = "onLongClick";
        Class clazz = classLoader.loadClass(HookActivity);
        XposedHelpers.findAndHookMethod(clazz, HookMethod,View.class, new XC_MethodHook() {
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                Intent intent = new Intent(ctx, classLoader.loadClass("com.coolapk.market.view.notification.NotificationActivity"));
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                intent.putExtra("tab", 0);
                ctx.startActivity(intent);
                param.setResult(true);
            }
        });
    }
```

**Comment by ejiaogl** [comment]
我改到<我>标签页里吧，因为我做了屏蔽<发现>标签

**Comment by Thiasap** [comment]
> 我改到<我>标签页里吧，因为我做了屏蔽<发现>标签

不知道方不方便改，我用发现页是它本身有长按的监听，换成别的可能需要重写com.coolapk.market.view.main.MainFragment下的一个OnLongClick函数

**Comment by 1767523953** [comment]
> > 我改到<我>标签页里吧，因为我做了屏蔽<发现>标签
> 
> 不知道方不方便改，我用发现页是它本身有长按的监听，换成别的可能需要重写com.coolapk.market.view.main.MainFragment下的一个OnLongClick函数

虽然不是具体到<我>标签页，但是把底栏的标签页全部都设置了OnLongClickListener，反正要的效果都一样，对吗？
```kotlin
        XposedHelpers.findAndHookMethod("com.coolapk.market.view.main.MainFragment", ContextUtil.classLoader, "setDiscoveryLongClick", object : XC_MethodHook(){
            override fun afterHookedMethod(param: MethodHookParam?) {
                super.afterHookedMethod(param)
                val mainFragment = param?.thisObject
                val mainFragmentBinding = XposedHelpers.getObjectField(mainFragment, "binding") as Object
                val bottomNavigation = XposedHelpers.getObjectField(mainFragmentBinding, "bottomNavigation") as Object
                val views = XposedHelpers.getObjectField(bottomNavigation, "views") as ArrayList<View>
                for (view in views){
                    view.setOnLongClickListener {
                        val intent = Intent(ContextUtil.context, XposedHelpers.findClass("com.coolapk.market.view.notification.NotificationActivity", ContextUtil.classLoader))
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                        intent.putExtra("tab", 0)
                        ContextUtil.context.startActivity(intent)
                        param?.result = true
                        return@setOnLongClickListener false
                    }
                }
            }
        })
```

**Comment by Thiasap** [comment]
> > > 我改到<我>标签页里吧，因为我做了屏蔽<发现>标签
> > 
> > 
> > 不知道方不方便改，我用发现页是它本身有长按的监听，换成别的可能需要重写com.coolapk.market.view.main.MainFragment下的一个OnLongClick函数
> 
> 虽然不是具体到<我>标签页，但是把底栏的标签页全部都设置了OnLongClickListener，反正要的效果都一样，对吗？
> 
> ```kotlin
>         XposedHelpers.findAndHookMethod("com.coolapk.market.view.main.MainFragment", ContextUtil.classLoader, "setDiscoveryLongClick", object : XC_MethodHook(){
>             override fun afterHookedMethod(param: MethodHookParam?) {
>                 super.afterHookedMethod(param)
>                 val mainFragment = param?.thisObject
>                 val mainFragmentBinding = XposedHelpers.getObjectField(mainFragment, "binding") as Object
>                 val bottomNavigation = XposedHelpers.getObjectField(mainFragmentBinding, "bottomNavigation") as Object
>                 val views = XposedHelpers.getObjectField(bottomNavigation, "views") as ArrayList<View>
>                 for (view in views){
>                     view.setOnLongClickListener {
>                         val intent = Intent(ContextUtil.context, XposedHelpers.findClass("com.coolapk.market.view.notification.NotificationActivity", ContextUtil.classLoader))
>                         intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
>                         intent.putExtra("tab", 0)
>                         ContextUtil.context.startActivity(intent)
>                         param?.result = true
>                         return@setOnLongClickListener false
>                     }
>                 }
>             }
>         })
> ```

对的效果都一样的，目的就是为了方便打开消息中心(或者其他界面)，谢谢大佬，大佬真棒🤪

**Comment by NextAlone** [comment]
功能已完成
