### ISSUE TITLE
xpatch版打不开模块设置

### ISSUE THREAD

**Issue by baseapk** [ejiaogl/FuckCoolapk#20]
![Screenshot_2021-03-12-01-20-20-054_com.coolapk.market.jpg](https://user-images.githubusercontent.com/29281332/110827525-1f4f5280-82d1-11eb-98ec-0e9316075377.jpg)

**Comment by AnyoeDove** [comment]
在应用转生上也是一样 应该是新加的图片banner 之前点击自定义水印也会报错

[BugXposed_error_20210312_013119.log](https://github.com/ejiaogl/FuckCoolapk/files/6124876/BugXposed_error_20210312_013119.log)

**Comment by t0HiiBwn** [comment]
这是由于 xpatch 使用了和 app 相同的 classloader 导致的，暂时想不出啥解决办法，现阶段也不保证 xpatch 版本的可用性，如果有解决办法，欢迎 pr

**Comment by t0HiiBwn** [comment]
已修复。
