### ISSUE TITLE
评论区

### ISSUE THREAD

**Issue by changyexing** [ejiaogl/FuckCoolapk#22]
昨晚更新0.4.1之后，关注页面所有动态  评论区加载失败

**Comment by ejiaogl** [comment]
什么时候更新的版本？ 昨天发过两个ci版本都是一样的

**Comment by changyexing** [comment]
github上的
![image](https://user-images.githubusercontent.com/47708150/111106515-340d3e00-8590-11eb-9061-029a4183f4e5.png)
目前已回退0.4，无问题

**Comment by changyexing** [comment]
哦 酷安版本是11.0.1

**Comment by ejiaogl** [comment]
已经测试无法复现该问题，上传日志吧

**Comment by changyexing** [comment]
该怎么获取日志呢...😂
