### ISSUE TITLE
动态的广告没有完全去除

### ISSUE THREAD

**Issue by APTX486** [ejiaogl/FuckCoolapk#28]
动态刷久了就会出现美团和饿了么的广告。
![Screenshot_2021-03-27-10-53-17-926_com coolapk market](https://user-images.githubusercontent.com/25340961/112708226-d70e6380-8e7e-11eb-9c13-b5d5abf3dc79.jpg)

**Comment by APTX486** [comment]
补充
![Uploading Screenshot_2021-03-30-19-24-00-116_com.coolapk.market.jpg…]()

**Comment by NextAlone** [comment]
已修复
