### ISSUE TITLE
建议：希望去除搜索框内广告、加入对初始搜索界面的精简

### ISSUE THREAD

**Issue by APTX486** [ejiaogl/FuckCoolapk#29]
搜索框里的广告、热门搜索、数码热榜、话题热榜，希望也能加开关去除
![Screenshot_2021-03-27-10-56-26-064_com coolapk market](https://user-images.githubusercontent.com/25340961/112708372-a0851880-8e7f-11eb-81d4-c3a98aaa68e3.jpg)

**Comment by 1767523953** [comment]
#55 #44 已完成
@NextAlone
