### ISSUE TITLE
开启防止链接追踪 链接打不开

### ISSUE THREAD

**Issue by HelloKitty2012** [ejiaogl/FuckCoolapk#33]
50版本可以打开链接，后续版本都打不开了

**Comment by t0HiiBwn** [comment]
浏览器：
coolapk 版本：
Android 版本：
log：

**Comment by HelloKitty2012** [comment]
酷安版本10.5.3
安卓10
miui11-3.27
浏览器via
webview87

**Comment by t0HiiBwn** [comment]
尝试更新到最新版 coolapk
针对非最新版 coolapk 的 issue 不会被解决

**Comment by HelloKitty2012** [comment]
> 尝试更新到最新版 coolapk
> 针对非最新版 coolapk 的 issue 不会被解决

感谢大佬
