### ISSUE TITLE
动态下边的评论区又被酷安云控了新的广告

### ISSUE THREAD

**Issue by APTX486** [ejiaogl/FuckCoolapk#34]
可恶:(
![Screenshot_2021-04-09-15-28-56-793_com coolapk market](https://user-images.githubusercontent.com/25340961/114154918-8834e500-98e6-11eb-8892-961a2325fa8e.jpg)

**Comment by xushet** [comment]
+1，在未登录的情况下也会显示![Screenshot_20210410-105237_酷安.png](https://user-images.githubusercontent.com/34502902/114256407-a46e7a00-99eb-11eb-90d3-604627675ed2.png)

**Comment by t0HiiBwn** [comment]
没了吧（
