### ISSUE TITLE
[BUG] 更改主题会导致自定义隐藏底部按钮错位

### ISSUE THREAD

**Issue by xushet** [ejiaogl/FuckCoolapk#36]
**情况描述？**
![Screenshot_20210411-125850_酷安.png](https://user-images.githubusercontent.com/34502902/114293076-b58bb980-9ac5-11eb-83c0-967ccfc1c0e4.png)
![Screenshot_20210411-125934_酷安.png](https://user-images.githubusercontent.com/34502902/114293081-c5a39900-9ac5-11eb-9a80-97fe56f8ae22.png)
![Screenshot_20210411-124853_酷安.png](https://user-images.githubusercontent.com/34502902/114292911-845eb980-9ac4-11eb-8d6b-c5179f6afd7c.png)
![Screenshot_20210411-125754_酷安.png](https://user-images.githubusercontent.com/34502902/114293059-8bd29280-9ac5-11eb-9d0a-3a7211327231.png)
![Screenshot_20210411-125803_酷安.png](https://user-images.githubusercontent.com/34502902/114293061-90974680-9ac5-11eb-93cf-c8b76922b485.png)
不知道算不算bug，影响不是很大，在更改去除底部按钮后，更改主题色后，“发现”变成了“首页，“应用”变成了“数码”，“我”变成了“发现”，
重启coolapk后bug消失，再次更换主题可复现

**对酷安生效的 Xposed 模块列表**
仅fuckcoolapk
**版本信息**
0.5.3xpatch版
Android:
Android11类原生
LSPosed:
1.3.4.5501
Coolapk:
11.1.2
Devices:
小米6
**相关日志**
暂无（或者不懂怎么抓）

**Comment by ejiaogl** [comment]
@xushet 这个bug还是在啊

**Comment by ketal178** [comment]
@ejiaogl 好耶

**Comment by t0HiiBwn** [comment]
和 activity 的生命周期有关系，暂时还没想好怎么修

**Comment by ketal178** [comment]
@t0HiiBwn 写一堆💩盖住就行，只要他能用，管他吃相难不难看
