### ISSUE TITLE
[BUG] 启用去除低栏按钮的bug

### ISSUE THREAD

**Issue by loIicon** [ejiaogl/FuckCoolapk#39]
**情况描述？**
启用去除低栏按钮功能，勾选去除数码、发现、应用游戏。
偶现打开酷安后 低栏处显示「首页」但实际是「数码」，低栏显示「我的」实际是「发现」
**对酷安生效的 Xposed 模块列表**
Fuckcoolapk
**版本信息**
Fuckcoolapk:0.5.3 20210410

Android:11

LSPosed:1.3.5(5551)

Coolapk:11.1.2

Devices:RedmiK30Pro

**相关日志**
由于此bug偶现，启用输出log后多次尝试无法复现，故暂缺。

**Comment by t0HiiBwn** [comment]
#36 
和这个问题的原因一致，目前还没想好怎么改。
