### ISSUE TITLE
[FR] 精简搜索结果界面多余的tab

### ISSUE THREAD

**Issue by xushet** [ejiaogl/FuckCoolapk#40]
**描述**:
精简搜索结果界面多余的tab
![Screenshot_20210415-114523_酷安.png](https://user-images.githubusercontent.com/34502902/114811109-137b1280-9de0-11eb-9477-9e8aef26110d.png)
例如搜索“lsposed”，大部分都是奔着动态tab去的，根本不需要数码、好物单等多余的tab，常常需要滑动好几次

**Comment by t0HiiBwn** [comment]
没必要，也不太好判断搜索哪些关键词隐藏哪些tab
