### ISSUE TITLE
[FR] 建议给开发者中心修改加一个开关

### ISSUE THREAD

**Issue by wherewhere** [ejiaogl/FuckCoolapk#42]
毕竟改后是跳转网页，对手机并没有什么优化，功能显得有点鸡肋，当然如果作者愿意写一个页面就更好了

**Comment by t0HiiBwn** [comment]
可是原来的不是更鸡肋，相当于没有（
为什么还要点进去呢（

**Comment by wherewhere** [comment]
> 可是原来的不是更鸡肋，相当于没有（
> 为什么还要点进去呢（

emmmm，至少原来还能直接看到我发了哪些东西，现在进去连界面都显示不全。。。

**Comment by t0HiiBwn** [comment]
点击自己的头像-首页-我开发的应用不就好

**Comment by wherewhere** [comment]
> 点击自己的头像-首页-我开发的应用不就好

我不管，我觉得不好，我就要说出来<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/src/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by t0HiiBwn** [comment]
坏耶，建议你来个pr（
不然我可懒得加开关耶！
