### ISSUE TITLE
[BUG] 无法打开酷安评论区的网址链接

### ISSUE THREAD

**Issue by fenglipop29** [ejiaogl/FuckCoolapk#43]
**情况描述？**

使用的是原版酷安，其他功能好像没问题，就是在网友评论区发的网址，我想点开网页链接，就会发现点不开。但是如果我关掉fuckcoolapk，则打开链接没问题

**版本信息**

Android:11

LSPosed:1.3.4

Coolapk:11.1.2

Devices:一加7t pro

fuckcoolapk 0.5.4
![photo_2021-04-20_15-59-29](https://user-images.githubusercontent.com/19856348/115359615-6f370880-a1f1-11eb-9aa5-c841ea6ccc3a.jpg)

**Comment by t0HiiBwn** [comment]
默认浏览器是？

**Comment by t0HiiBwn** [comment]
不知道了耶（
下个版本试试换个hook点（

**Comment by xushet** [comment]
chrome canary，能一切正常打开
![Screenshot_20210425-134342_酷安.png](https://user-images.githubusercontent.com/34502902/115982267-50a78780-a5cc-11eb-8c86-773bcf9e5996.png)

**Comment by 1767523953** [comment]
现在还有这个问题吗，理论上应该是没有的

**Comment by fenglipop29** [comment]
更新到最新版，没有这个问题了
