### ISSUE TITLE
[BUG] 0.5.2版本之后，酷安只要进入后台就会触发#36问题

### ISSUE THREAD

**Issue by APTX486** [ejiaogl/FuckCoolapk#56]
**情况描述？**

启用自定义低栏，仅保留首页和我的，酷安每次进入后台，或者切换到其他应用，再次打开酷安，必现按钮错位，重启酷安恢复，但下一次还是会复现，复现频率非常高，基本是100%，十分影响使用。
![Screenshot_2021-04-29-23-35-43-902_com coolapk market](https://user-images.githubusercontent.com/25340961/116579374-f2ceb480-a8d7-11eb-8ccd-615349223869.jpg)
看到大佬在#36问题下的回复了，该问题暂时无解，所以能否暂时回退到旧版（0.5.2）对低栏的修改方式？虽然无法自定义，但起码保证了酷安的正常使用。

**对酷安生效的 Xposed 模块列表**

仅本模块（fuckcoolapk）

**版本信息**

基于Android 11的MIUI 12.5

LSPosed:1.3.5

Coolapk:11.1.5.1

Devices:小米9 开发版21.4.21

**相关日志**

**Comment by t0HiiBwn** [comment]
https://github.com/ejiaogl/FuckCoolapk/commit/3ebab5346e0cc0a9d94222a5673cf370410d3f35

应该已经修复了，等发版。
