### ISSUE TITLE
菜单去哪了

### ISSUE THREAD

**Issue by Miuzarte** [ejiaogl/FuckCoolapk#8]
![Screenshot_2021-03-03-18-04-58-586_org meowcat edxposed manager](https://user-images.githubusercontent.com/66856838/109789154-aa479300-7bd5-11eb-9928-968d42a01fa6.jpg)
![Screenshot_2021-03-03-18-04-50-828_com coolapk market](https://user-images.githubusercontent.com/66856838/109789166-ac115680-7bd5-11eb-9cc8-4e9aeb379a30.jpg)

**Comment by ejiaogl** [comment]
麻烦日志发一下

**Comment by Miuzarte** [comment]
8MB的txt，直接发还是。。。

**Comment by ejiaogl** [comment]
> 8MB的txt，直接发还是。。。

你先清掉原有日志，重新打开傻安再上传日志

**Comment by Miuzarte** [comment]
> 03-03 18:47:16.299 19298 19298 I EdXposed: Start to install inline hooks
03-03 18:47:16.299 19298 19298 I EdXposed: Using api level 30
03-03 18:47:16.299 19298 19298 I EdXposed: Start to install Riru hook
03-03 18:47:16.319 19298 19298 I EdXposed: Riru hooks installed
03-03 18:47:16.328 19298 19298 I EdXposed: ART hooks installed
03-03 18:47:16.353 19298 19298 I EdXposed: Loading modules for com.coolapk.market
03-03 18:47:16.354 19298 19298 I EdXposed-Bridge: Loading modules from /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/base.apk
03-03 18:47:16.354 19298 19298 E EdXposed-Bridge:   File does not exist
03-03 18:47:16.354 19298 19298 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 18:47:16.415 19298 19298 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 18:47:16.416 19298 19298 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 18:47:16.476 19298 19298 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 18:47:27.778 19718 19718 I EdXposed: Start to install inline hooks
03-03 18:47:27.778 19718 19718 I EdXposed: Using api level 30
03-03 18:47:27.778 19718 19718 I EdXposed: Start to install Riru hook
03-03 18:47:27.798 19718 19718 I EdXposed: Riru hooks installed
03-03 18:47:27.808 19718 19718 I EdXposed: ART hooks installed
03-03 18:47:27.833 19718 19718 I EdXposed: Loading modules for com.google.android.documentsui
03-03 18:47:27.833 19718 19718 I EdXposed-Bridge: Loading modules from /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/base.apk
03-03 18:47:27.833 19718 19718 E EdXposed-Bridge:   File does not exist
03-03 18:47:27.833 19718 19718 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 18:47:27.895 19718 19718 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 18:47:27.896 19718 19718 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 18:47:27.955 19718 19718 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 18:47:28.405 19751 19751 I EdXposed: Start to install inline hooks
03-03 18:47:28.405 19751 19751 I EdXposed: Using api level 30
03-03 18:47:28.405 19751 19751 I EdXposed: Start to install Riru hook
03-03 18:47:28.428 19751 19751 I EdXposed: Riru hooks installed
03-03 18:47:28.439 19751 19751 I EdXposed: ART hooks installed
03-03 18:47:28.467 19751 19751 I EdXposed: Loading modules for com.android.externalstorage
03-03 18:47:28.467 19751 19751 I EdXposed-Bridge: Loading modules from /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/base.apk
03-03 18:47:28.467 19751 19751 E EdXposed-Bridge:   File does not exist
03-03 18:47:28.467 19751 19751 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 18:47:28.539 19751 19751 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 18:47:28.540 19751 19751 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 18:47:28.611 19751 19751 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 18:47:29.846 19784 19784 I EdXposed: Start to install inline hooks
03-03 18:47:29.846 19784 19784 I EdXposed: Using api level 30
03-03 18:47:29.846 19784 19784 I EdXposed: Start to install Riru hook
03-03 18:47:29.865 19784 19784 I EdXposed: Riru hooks installed
03-03 18:47:29.875 19784 19784 I EdXposed: ART hooks installed
03-03 18:47:29.896 19784 19784 I EdXposed: Loading modules for com.android.settings:remote
03-03 18:47:29.896 19784 19784 I EdXposed-Bridge: Loading modules from /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/base.apk
03-03 18:47:29.896 19784 19784 E EdXposed-Bridge:   File does not exist
03-03 18:47:29.896 19784 19784 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 18:47:29.961 19784 19784 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 18:47:29.962 19784 19784 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 18:47:30.026 19784 19784 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit

**Comment by t0HiiBwn** [comment]
```
EdXposed-Bridge: Loading modules from /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/base.apk
03-03 18:47:16.354 19298 19298 E EdXposed-Bridge: File does not exist
03-03 18:47:16.354 19298 19298 I
```
edxp有问题

**Comment by t0HiiBwn** [comment]
`ls /data/app/~~rSfjdd2Z-NRWV1h8b_I1iQ==/com.fuckcoolapk-dHW-kJG2K_N4dsRfXfkf6w==/`

看下？

**Comment by Miuzarte** [comment]
![Screenshot_2021-03-03-22-43-54-888_bin mt plus](https://user-images.githubusercontent.com/66856838/109822539-a9762780-7bfc-11eb-88b8-98b7867e0cb2.jpg)
没这个路径

**Comment by t0HiiBwn** [comment]
删了重装试试？

**Comment by Miuzarte** [comment]
> 删了重装试试？

还是没有

> 03-03 22:49:59.643  9686  9686 I EdXposed: Start to install inline hooks
03-03 22:49:59.643  9686  9686 I EdXposed: Using api level 30
03-03 22:49:59.643  9686  9686 I EdXposed: Start to install Riru hook
03-03 22:49:59.661  9686  9686 I EdXposed: Riru hooks installed
03-03 22:49:59.672  9686  9686 I EdXposed: ART hooks installed
03-03 22:49:59.692  9686  9686 I EdXposed: Loading modules for com.coolapk.market
03-03 22:49:59.692  9686  9686 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:49:59.750  9686  9686 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:49:59.751  9686  9686 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:49:59.807  9686  9686 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 22:50:06.739   862   862 E EdXposed: can't parse /data/system
03-03 22:50:07.529 10088 10088 I EdXposed: Start to install inline hooks
03-03 22:50:07.529 10088 10088 I EdXposed: Using api level 30
03-03 22:50:07.529 10088 10088 I EdXposed: Start to install Riru hook
03-03 22:50:07.573 10088 10088 I EdXposed: Riru hooks installed
03-03 22:50:07.585 10088 10088 I EdXposed: ART hooks installed
03-03 22:50:07.612 10088 10088 I EdXposed: Loading modules for com.milink.service
03-03 22:50:07.612 10088 10088 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:50:07.688 10088 10088 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:50:07.688 10088 10088 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:50:07.757 10088 10088 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 22:50:08.625 10122 10122 I EdXposed: Start to install inline hooks
03-03 22:50:08.625 10122 10122 I EdXposed: Using api level 30
03-03 22:50:08.625 10122 10122 I EdXposed: Start to install Riru hook
03-03 22:50:08.648 10122 10122 I EdXposed: Riru hooks installed
03-03 22:50:08.660 10122 10122 I EdXposed: ART hooks installed
03-03 22:50:08.689 10122 10122 I EdXposed: Loading modules for com.google.android.documentsui
03-03 22:50:08.689 10122 10122 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:50:08.765 10122 10122 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:50:08.766 10122 10122 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:50:08.839 10122 10122 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 22:50:09.259 10154 10154 I EdXposed: Start to install inline hooks
03-03 22:50:09.259 10154 10154 I EdXposed: Using api level 30
03-03 22:50:09.259 10154 10154 I EdXposed: Start to install Riru hook
03-03 22:50:09.294 10154 10154 I EdXposed: Riru hooks installed
03-03 22:50:09.305 10154 10154 I EdXposed: ART hooks installed
03-03 22:50:09.333 10154 10154 I EdXposed: Loading modules for com.android.shell
03-03 22:50:09.333 10154 10154 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:50:09.403 10154 10154 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:50:09.404 10154 10154 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:50:09.471 10154 10154 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 22:50:09.630 10177 10177 I EdXposed: Start to install inline hooks
03-03 22:50:09.630 10177 10177 I EdXposed: Using api level 30
03-03 22:50:09.630 10177 10177 I EdXposed: Start to install Riru hook
03-03 22:50:09.649 10177 10177 I EdXposed: Riru hooks installed
03-03 22:50:09.658 10177 10177 I EdXposed: ART hooks installed
03-03 22:50:09.683 10177 10177 I EdXposed: Loading modules for com.android.traceur
03-03 22:50:09.683 10177 10177 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:50:09.752 10177 10177 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:50:09.753 10177 10177 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:50:09.821 10177 10177 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
03-03 22:50:10.015 10199 10199 I EdXposed: Start to install inline hooks
03-03 22:50:10.015 10199 10199 I EdXposed: Using api level 30
03-03 22:50:10.015 10199 10199 I EdXposed: Start to install Riru hook
03-03 22:50:10.037 10199 10199 I EdXposed: Riru hooks installed
03-03 22:50:10.047 10199 10199 I EdXposed: ART hooks installed
03-03 22:50:10.070 10199 10199 I EdXposed: Loading modules for com.github.kr328.clash:background
03-03 22:50:10.070 10199 10199 I EdXposed-Bridge: Loading modules from /data/app/~~B4Wf7IVk6cw1eiJjoArUoQ==/com.huanchengfly.miui.checker-9qL2Iin7-KYEf08N-N4oMw==/base.apk
03-03 22:50:10.136 10199 10199 I EdXposed-Bridge:   Loading class com.huanchengfly.miui.checker.xposed.FullDeviceLevelModule
03-03 22:50:10.137 10199 10199 I EdXposed-Bridge: Loading modules from /data/app/~~pMeaIRuS6bLYo3uTq0Zj8g==/com.fkzhang.qqxposed-zYJvwl8SPrijBeH6GJaukw==/base.apk
03-03 22:50:10.195 10199 10199 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit

**Comment by t0HiiBwn** [comment]
去管理器重新开关模块

**Comment by Miuzarte** [comment]
> 去管理器重新开关模块

这样就行了草，我刚刚卸载重启安装重启都没解决
