### ISSUE TITLE
[BUG] _____闪退_________

### ISSUE THREAD

**Issue by wdnmd030** [ejiaogl/FuckCoolapk#82]
**情况描述？**开了模块启动闪退，关了就能进

**对酷安生效的 Xposed 模块列表：**无

**版本信息：**11.2.6.1

Android:11

LSPosed:1.5

Coolapk:11.2.6.1

Devices:0.0

**相关日志：**

**Comment by Dearlesliezyy** [comment]
+1

**Comment by ninggee** [comment]
开了模块，酷安直接闪退

**Comment by daiyuxiang520** [comment]
我也是闪退

**Comment by t0HiiBwn** [comment]
请使用 11.1.5.1
