### ISSUE TITLE
[BUG] Android12 不可用

### ISSUE THREAD

**Issue by diandianti** [ejiaogl/FuckCoolapk#97]
https://github.com/ejiaogl/FuckCoolapk/releases/tag/0.5.8-Android12
这个版本，我直接安装的完整版的apk包https://github.com/ejiaogl/FuckCoolapk/releases/download/0.5.8-Android12/Coolapk11.1.5.1.with.fuckcoolapk.support.android12.apk
点击酷安-设置-Fuck Coolapk酷安就闪退

**Comment by 1767523953** [comment]
@diandianti 没日志神仙来了也没办法

**Comment by Alexhhhc** [comment]
试试这个https://t.me/fuck_coolapk/80

**Comment by diandianti** [comment]
> 试试这个https://t.me/fuck_coolapk/80

感谢，但是已经刷回安卓11了
